# File: .github/workflows/merly-mentor-check.yml
name: Merly Mentor Check
on:
  push:
    branches:
      - main
  pull_request:      # triggers on PRs into any branch

jobs:
  merly-check:
    runs-on: ubuntu-latest
    env:
      MM_KEY: ${{ secrets.MM_KEY }}
      MM_INSTALL_DIR: merly-install

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install MPCC Universal (staging)
        timeout-minutes: 10
        run: |
          echo "::add-mask::${MM_KEY}"
          mkdir -p "${MM_INSTALL_DIR}"
          cd "${MM_INSTALL_DIR}"
          curl -fsSL https://raw.githubusercontent.com/merly-ai/MPCC-Universal/main/install.sh \
            | bash -s -- -q -k "${MM_KEY}" install --staging

      - name: Run MerlyMentor and annotate
        timeout-minutes: 4
        shell: bash
        run: |
          echo "::add-mask::${MM_KEY}"
          cd "${MM_INSTALL_DIR}"

          # 1) capture all output
          OUT=$(./MerlyMentor-Staging --github-actions -D "${GITHUB_WORKSPACE}" check 2>&1)

          # 2) echo raw for full context
          echo "$OUT"