# File: .github/workflows/merly-mentor-check.yml
name: Merly Mentor Check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-container:
    runs-on: ubuntu-latest
    env:
      MODEL_PATH: /data/.models/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run container with entrypoint
        run: |
          docker run --rm \
            -e REGISTRATION_KEY="${{ secrets.MM_KEY }}" \
            -e REPO="/repo" \
            -e mm_models_root="${{ env.MODEL_PATH }}" \
            -v "${{ github.workspace }}:/repo" \
            -e GITHUB_STEP_SUMMARY="$GITHUB_STEP_SUMMARY" \
            -v "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
            merlyai/mentor:v0.7.9 -D /repo --github-actions check ${{ inputs.debug == 'true' && '--debug --stdout' || '' }}