# File: .github/workflows/test-check-mp.yml
name: Test Merly Mentor Action

# Trigger on pushes to main (or whatever branch)
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-merly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          path: testpath

      - name: Merly Mentor Check MP
        uses: leeboydmerly/merly-mentor-action@v1.0.19-beta
        with:
          mm-key: ${{ secrets.MM_KEY }}
          checkout-code: false
          debug: true
          path: testpath
          max-issues: 15